VARIABLE FP_BASE
VARIABLE FP_EXP
10 FP_BASE !
0  FP_EXP !

: NORMAL 10 FP_BASE !   0 FP_EXP ! ;
: MONEY  10 FP_BASE !  -2 FP_EXP ! ;
: KILO   10 FP_BASE !   3 FP_EXP ! ;

: MUL * ;
: DIV / ;

: POW ( b e -- b^e )
    DUP 0 < ABORT" FixP: NEG EXP"
    2DUP OR 0 = ABORT" FixP: 0^0"
    1 SWAP 0 ?DO  OVER *  LOOP NIP
;

: NEGPOW ARITHMETICAL_NOT POW ;

: *
    MUL FP_BASE @
    FP_EXP @ DUP 0 <
    IF  NEGPOW DIV  ELSE  POW MUL  THEN
;

: /
    DIV FP_BASE @
    FP_EXP @ DUP 0 <
    IF  NEGPOW MUL  ELSE  POW DIV  THEN
;

: FIX> 1 1 / DIV ;
: >FIX 1 1 / MUL ;
